.TH KBDATE 1
.SH NAME
kbdate \- Creates a date-based knowledge base identifier.
.SH SYNOPSIS
.B kbdate
.SH DESCRIPTION
.B kbdate creates a date-based knowledge base ID in KBYYMMmmmmm format. 
YY is the two-digit year. 
MM is the two-digit month. 
mmmmm is the five-digit number of minutes elapsed since the start of the MM month.
