.TH KBDATE 1
.SH NAME
kbdate \- Creates a date-based knowledge base identifier.
.SH SYNOPSIS
.B kbdate
.SH DESCRIPTION
.B kbdate creates a date-based knowledge base ID in KBYYMMmmmmm format.
.pp \- YY is the two-digit year.
.pp \- MM is the two-digit month.
.pp \- mmmmm is the number of minutes elapsed since the MM month started.
\&
.pp
