.TH KBDATE 1
.SH NAME
kbdate \- Creates a date-based knowledge base identifier.
.SH SYNOPSIS
.B kbdate
.SH DESCRIPTION
.B kbdate
Creates a date-based knowledge base ID in KBYYMMmmmmm format.
YY is the two-digit year.
MM is the two-digit month.
mmmmm is the number of minutes elapsed since the MM month started.
